version: '3.8'

services:
  # -------------------- EXAM SERVICE --------------------
  exam-service:
    build: ./exam-service
    container_name: exam-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=localhost
    networks:
      - skillnet

  # -------------------- SESSION SERVICE --------------------
  session-service:
    build: ./session-service
    container_name: session-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_RABBITMQ_HOST=localhost
    networks:
      - skillnet

  # -------------------- USER SERVICE --------------------
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_RABBITMQ_HOST=localhost
    networks:
      - skillnet

# Shared network for all microservices
networks:
  skillnet:
    driver: bridge
